name: "PR時のブランチ制限&検証"

on:
  pull_request:
    branches:
      - main
      - develop #developブランチも対象にする

jobs:
  check_base_branch:
    name: "PRのベースブランチをチェック"
    runs-on: ubuntu-latest

    steps:
      - name: "リポジトリをチェックアウト"
        uses: actions/checkout@v4

      - name: "ブランチ制限チェック"
        run: |
          TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"

          echo "ターゲットブランチ: $TARGET_BRANCH"
          echo "ソースブランチ: $SOURCE_BRANCH"

          if [[ $TARGET_BRANCH == "main" ]]; then
            if [[ $SOURCE_BRANCH != "develop"]]; then
              echo "エラー：mainブランチへのPRはdevelopブランチからのみ可能です。"
              echo "まずdevelopブランチにPRを出してください"
              exit 1
            else
              echo "正常：developブランチからのPRです"
            fi
          elif [[ TARGET_BRANCH == "develop"]]; then
            echo "正常：developブランチへのPRです"
          fi
      
      - name: "PR情報を表示"
        run: |
          echo "PR情報"
          echo " - ブランチ: ${{github.event.pull_request.head.ref}} => ${{github.event.pull_request.base.ref}}"
          echo " - タイトル: ${{github.event.pull_request.title}}"
          echo " - 作成者: ${{github.event.pull_request.user.login}}"